# This action comments on a PR by a community member with the expectations they
# should have for the process. It only runs on PRs to the main branch when they
# are opened. It uses a markdown file in the .github folder for the content.
name: Sharing Expectations
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  ShareExpectations:
    if: |
      github.event.pull_request.author_association == 'CONTRIBUTOR' ||
      github.event.pull_request.author_association == 'FIRST_TIMER' ||
      github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' ||
      github.event.pull_request.author_association == 'NONE'
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    # Limits this job to only run on PRs where the author is not part of the
    # maintainer team (i.e. not a collaborator, member, or owner).
    steps:
        # The repo needs to be checked out to have access to the message file.
      - name: Checkout
        id: checkout_repo
        uses: actions/checkout@v3
        # Builds the list of author associations the message should post for
      # - name: List Author Associations to Comment On
      #   id: get_associations
      #   run: |
      #     $Associations = @(
      #       'CONTRIBUTOR'
      #       'FIRST_TIMER'
      #       'FIRST_TIME_CONTRIBUTOR'
      #       'NONE'
      #     ) | ConvertTo-Json -Compress
      #     echo "::set-output name=value::$Associations"
      #   # Comments on the PR
      - name: Comment on Community PR
        id: comment_on_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $Number = ${{ github.event.pull_request.number }}
          $Repo = '${{ github.repository_owner }}/${{ github.event.repository.name }}'
          $BodyFile = Get-Item -Path ./.github/messages/Expectations.md |
            Select-Object -ExpandProperty FullName
          gh pr comment $Number --repo $Repo --body-file "$BodyFile"
