name: Targeting Valid Branch
on: [pull_request_target]
jobs:
  Test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: List info
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "Targeting: ${{ github.base_ref }}"
          $Owner, $Repo = "${{ github.repository }}" -split "/"
          echo "Repo Owner: $Owner"
          echo "Repo Name:  $Repo"
          echo "For PR: ${{ github.event.number}}"
          $Query = @'
          query($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
              pullRequest(number: 8695) {
                author {
                  login
                }
                authorAssociation
              }
            }
          }
          '@
          echo "Query: $Query"
          $JQ = '.data.repository.pullRequest | {author, authorAssociation}'
          echo "JQ: $JQ"
          $ApiResults = gh api graphql -F owner=$Owner -F repo=$Repo -f query=$Query --jq $JQ
          echo "API Results:`n$($ApiResults)"
          # $Permission = gh repo view ${{ github.repository }} --json 'viewerPermission'
          # echo "$Permission"
          # echo "$($Permission | ConvertFrom-Json -ErrorAction Stop)"
          # echo "$($Permission | ConvertFrom-Json | Select -Expand viewerPermission)"
      # - name: Authorized to Target Live Branch?
      #   if: ${{ github.base_ref == 'live' }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     $Permission = gh repo view ${{ github.repository }} --json 'viewerPermission'
      #     | ConvertFrom-Json
      #     | Select-Object -ExpandProperty viewerPermission
      #     if ($Permission -notin @('WRITE', 'ADMIN')) {
      #       throw "User ${{ github.actor }} does not have permissions to target live branch."
      #     } else {
      #       echo "User has permissions to target live branch."
      #     }
